- name: Reset to remote state
      run: |
        git fetch origin main
        git reset --hard origin/main
    - name: Make changes
      run: |
        echo "Dernière mise à jour automatique : $(date)" >> update_log.txt
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Mise à jour automatique - $(date)" || echo "No changes to commit"
        git push origin main
