name: Automated Commit and Push

on:
  schedule:
    - cron: '0 */12 * * *' # Ce cron job s'exécutera toutes les 12 heures

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Tu peux adapter à ta version de node
    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-commit - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
