name: Automated Commit and Push

on:
  schedule:
    - cron: '0 */12 * * *' # Toutes les 12 heures
  workflow_dispatch: # Permet l'exécution manuelle

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Pull latest changes
      run: |
        git pull origin main
    - name: Make changes
      run: |
        # Ajoutez ici les commandes pour effectuer les changements souhaités
        # Par exemple :
        echo "Dernière mise à jour automatique : $(date)" >> update_log.txt
    - name: Commit and push if there are changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour automatique - $(date)" && git push)
