name: Automated Commit and Push

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Fetch latest changes
        run: git pull origin main
      - name: Make changes and commit
        run: |
          git config --global user.email "ton-email@example.com"
          git config --global user.name "Auto Commit Bot"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated commit"
      - name: Push changes back to GitHub
        run: |
          git push origin main || (git pull --rebase origin main && git push origin main)
